# Generated by Django 4.2.7 on 2023-11-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0002_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token',
            new_name='gitlab_token',
        ),
    ]
