# Generated by Django 4.2.7 on 2023-11-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0003_rename_token_user_gitlab_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gitlab_token',
            field=models.CharField(blank=True, default=None, help_text='Gitlab personal token', max_length=40, null=True),
        ),
    ]
