# Generated by Django 4.2.7 on 2023-12-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0004_alter_user_gitlab_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_id', models.IntegerField()),
                ('name', models.CharField()),
                ('description', models.CharField(blank=True, default=None, null=True)),
                ('url', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(to='export.project'),
        ),
    ]
