# Generated by Django 4.2.7 on 2023-12-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0005_project_user_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='project',
            name='gitlab_id',
            field=models.IntegerField(unique=True),
        ),
    ]
